#!/usr/bin/env python
"""
SpaceTime Engine — Complexified Framework Demonstration
========================================================

This script demonstrates the key capabilities of the upgraded
spacetimeengine, with focus on the complexified metric framework
from "On the Electrodynamics of Geodesic Motion."

Demonstrations:
  1. Standard Schwarzschild (backward compatibility check)
  2. Complexified Reissner-Nordström (EM self-energy from geometry)
  3. Static Coulomb field (Maxwell from imaginary curvature)
  4. Extremality analysis (Q/M vs √(G/k))
  5. Temporal hypersphere with EM sector
"""

import sys
import os
# Navigate up to the directory containing spacetimeengine/
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))

from sympy import symbols, sqrt, pprint, Eq, Symbol, simplify, pi
from spacetimeengine.src.spacetime import SpaceTime
from spacetimeengine.src.complex_spacetime import (
    ComplexSpaceTime, complexified_from_potentials, kappa_sym
)
from spacetimeengine.src.solutions import Solution


def separator(title):
    print("\n" + "█" * 70)
    print(f"  {title}")
    print("█" * 70 + "\n")


def demo_standard_schwarzschild():
    """Demo 1: Standard Schwarzschild — verifies backward compatibility."""
    separator("DEMO 1: Standard Schwarzschild (backward compatibility)")

    sol = Solution()
    st = SpaceTime(sol.schwarzschild(), suppress_printing=True)

    print("Metric: Schwarzschild (static, uncharged, non-rotating)")
    print("Coordinates: [t, r, θ, φ]")

    print("\nNon-zero connection coefficients:")
    print("-" * 40)
    st.print_nonzero_connections("udd")

    print("\nEinstein tensor (should be all zero for vacuum):")
    st.print_nonzero_einstein("dd")

    print(f"\nRicci scalar R = {st.get_ricci_scalar()}")
    print("✓ Schwarzschild is Ricci-flat as expected.\n")


def demo_complexified_rn():
    """Demo 2: Reissner-Nordström from the complexified framework."""
    separator("DEMO 2: Complexified Reissner-Nordström")

    print("""
    The RN charge correction r_Q²/r² is NOT inserted by hand.
    It is GENERATED by the −κ²CC self-energy of the imaginary
    connection, through the same mechanism that produces
    gravitational self-energy in standard GR.

    Complex metric: g̃_μν = g_μν + iκ e_μν
    where e_{00} = −2kQ/(c²r), all other e_{μν} = 0
    """)

    sol = Solution()
    real_sol, e_mn = sol.complexified_reissner_nordstrom()

    cst = ComplexSpaceTime(real_sol, e_mn, suppress_printing=True)

    # Show the complex metric
    cst.print_complex_metric()

    # Show EM self-energy
    cst.print_em_self_energy_summary()

    # Show the imaginary connection
    print("\nImaginary Connection C^α_{μν} (Coulomb field in geometric language):")
    print("-" * 55)
    for a in cst.dimensions:
        for m in cst.dimensions:
            for n in cst.dimensions:
                val = cst.get_imaginary_connection(a, m, n)
                if val != 0:
                    pprint(Eq(Symbol(f'C^{a}_{m}{n}'), val))
                    print()

    print("""
    KEY RESULT: The −κ²CC terms have index contractions IDENTICAL to
    the gravitational ΓΓ terms, with sign reversal from i² = −1.
    This is the geometric origin of electromagnetic repulsion.
    """)


def demo_coulomb_field():
    """Demo 3: Extract Maxwell's equations from imaginary curvature."""
    separator("DEMO 3: Coulomb Field — Maxwell from Geometry")

    print("""
    Starting from flat Minkowski + Coulomb perturbation e_{00} = −2kQ/(c²r)
    
    The imaginary sector of G̃_μν = 0 should produce:
      - Gauss's law: ∇·E = 4πk ρ_q
      - No-source exterior: ∇²φ = 0  (for r > 0)
    
    The EM field tensor F_μν emerges from imaginary curvature:
      R^(e)_{0i0j} ∝ F_{ij}/c²
    """)

    sol = Solution()
    real_sol, e_mn = sol.complexified_coulomb_static()

    cst = ComplexSpaceTime(real_sol, e_mn, suppress_printing=True)

    print("EM field tensor F_μν (extracted from imaginary curvature):")
    print("-" * 55)
    for mu in cst.dimensions:
        for nu in cst.dimensions:
            val = cst.em_field_tensor_dd[mu, nu]
            if val != 0:
                pprint(Eq(Symbol(f'F_{mu}{nu}'), val))
                print()

    print("\nCurrent density tensor J_μν:")
    print("-" * 30)
    for mu in cst.dimensions:
        for nu in cst.dimensions:
            val = cst.current_density_dd[mu, nu]
            if val != 0:
                pprint(Eq(Symbol(f'J_{mu}{nu}'), val))
                print()

    print("""
    In the exterior region (r > 0), the imaginary Einstein tensor
    should vanish — confirming that the Coulomb field satisfies
    the source-free Maxwell equations on the curved background.
    """)


def demo_extremality():
    """Demo 4: Extremality analysis Q/M = √(G/k)."""
    separator("DEMO 4: Extremality Analysis")

    print("""
    The extremal RN condition occurs when the real and imaginary
    perturbation magnitudes are exactly balanced:
    
        |κ·e_{00}| / |h_{00}| = 1  ⟺  Q/M = √(G/k) = κ
    
    This same ratio appears throughout the framework:
      1. Complex metric coupling: g̃ = g + iκe
      2. Imaginary mass-energy interface (Section 3)
      3. Extremal black hole threshold (Section 6)
      4. Net charge-to-mass ratio of the cosmos (Section 7)
    """)

    G, M, k, Q, c = symbols('G M k Q c', positive=True)

    # Compute perturbation ratio
    h_00 = 2 * G * M / (c**2)   # ∝ r_s (at r=1 for simplicity)
    e_00 = 2 * k * Q / c**2
    kappa = sqrt(G / k)

    ratio = simplify(kappa * e_00 / h_00)
    print("Perturbation ratio |κ·e_{00}| / |h_{00}|:")
    pprint(Eq(Symbol('ratio'), ratio))

    print("\nAt extremality Q/M = κ:")
    ratio_at_extremal = ratio.subs(Q, kappa * M)
    pprint(Eq(Symbol('ratio|_{extremal}'), simplify(ratio_at_extremal)))

    print(f"\n  → ratio = {simplify(ratio_at_extremal)} ✓")

    # Cosmic extremality
    print("\n\nCosmic Extremality:")
    print("-" * 30)
    print("If R_S = ct (Schwarzschild radius = Hubble radius):")
    print("  M_U = c³t/(2G)")
    print("  Q_U = √(G/k) · M_U")
    print("  → Q_U/M_U = √(G/k) = κ  ← EXTREMAL")
    print("\n  The universe sits at exact real-imaginary balance.")


def demo_convenience_constructor():
    """Demo 5: Building complexified spacetime from potentials."""
    separator("DEMO 5: Convenience Constructor — From Potentials")

    print("""
    The complexified_from_potentials() function maps standard
    electromagnetic potentials (φ, A) to the imaginary metric
    perturbation e_μν:
    
        e_{00} = −2φ/c²
        e_{0i} = −A_i/c²
        e_{ij} = 0
    """)

    sol = Solution()
    k, Q, c = symbols('k Q c')
    r = symbols('r')

    # Build from Coulomb potential
    phi = k * Q / r
    cst = complexified_from_potentials(
        sol.minkowski_spherical(),
        phi_expr=phi,
        suppress_printing=True
    )

    print("Built from φ = kQ/r:")
    print(f"  e_00 = {cst.e_dd[0, 0]}")
    print(f"  e_01 = {cst.e_dd[0, 1]}")
    print(f"  e_11 = {cst.e_dd[1, 1]}")
    print("\nFull e_μν matrix:")
    pprint(cst.e_dd)


def demo_summary():
    """Print a theory summary."""
    separator("FRAMEWORK SUMMARY")

    print("""
    The Complexified Einstein Field Equations
    ==========================================
    
    Unified field equation:     G̃_μν = 0
    Complex metric:             g̃_μν = g_μν + iκ e_μν
    Coupling constant:          κ = √(G/k) ≈ 8.617 × 10⁻¹¹ C/kg
    
    Separation into sectors:
    ┌──────────────────────────────────────────────────────────┐
    │  Re(G̃_μν) = 0  →  Einstein eqs + EM self-energy       │
    │                     G_μν[g] = −ΔG^(EM)_μν              │
    │                     (gravity + charge curvature)         │
    │                                                          │
    │  Im(G̃_μν) = 0  →  Maxwell's equations                 │
    │                     G^(e)_μν = (8πk/c⁴) J_μν           │
    │                     (EM from geometry)                   │
    └──────────────────────────────────────────────────────────┘
    
    Self-energy mechanism:
      Γ̃Γ̃ = ΓΓ − κ²CC + iκ(ΓC + CΓ)
             ↑        ↑          ↑
        grav self  EM self   cross-coupling
        energy     energy    
                   (i²=−1)
    
    Key predictions beyond standard Maxwell theory:
      • J_μν rank-2 source (10 components vs 4 in J^μ)
      • 3 new current conservation laws: ∂_t j^j + ∂_i Σ^{ij} = 0
      • Charge pressure λ from thermal charge carrier motion
      • 8 total conservation laws (vs 5 in Einstein-Maxwell)
    
    Validated against:
      ✓ Schwarzschild (purely real limit, e_μν = 0)
      ✓ Reissner-Nordström (r_Q²/r² from −κ²CC)
      ✓ Lorentz force (from complex geodesic projection)
      ✓ Maxwell's equations (from Bianchi identity + Im(G̃) = 0)
    """)


# ======================================================================
#  MAIN
# ======================================================================

if __name__ == "__main__":
    print("\n" + "═" * 70)
    print("  SPACETIME ENGINE — Complexified Framework Demonstration")
    print("  Based on: 'On the Electrodynamics of Geodesic Motion'")
    print("  by Michael C. Ryan")
    print("═" * 70)

    # Run demos (comment out for faster execution)
    demo_summary()
    demo_standard_schwarzschild()
    demo_complexified_rn()
    demo_coulomb_field()
    demo_extremality()
    demo_convenience_constructor()

    print("\n" + "═" * 70)
    print("  All demonstrations complete.")
    print("═" * 70 + "\n")
